### PR TITLE
fix: correct button URL on service pages

### LINKED ISSUE #53: Penetration test service page incorrect URL linked in button
The "Show Projects" button redirects to the product design portfolio rather it should to VAPT portfolio.
image

URL: https://tecvity.co/our-services/penetration-testing

### PR DESCRIPTION
**Pull request by saadamir3180**
checks if the portfolio link exists in service, only then render the show projects button

closes #53

### CODE REVIEW

File: components/service/components/ServiceDetails.jsx [hunk 1]
```diff
@@ -144,15 +144,17 @@ export default function ServiceDetails({ serviceTitle }) {
             <p className="sec-text mb-n1 mt-40 space-bottom">
             {serviceItem?.para7}
             <div className="col-auto d-none d-lg-block">
+            {serviceItem?.portfolioLink && serviceItem.portfolioLink !== "" && (
                   <div className="service-portfolio-button">
-                    <Link scroll={false} href="/our-portfolio/pd" className="btn">
+                    <Link scroll={false} href={serviceItem.portfolioLink} className="btn">
```
Comment (njmulsqb) [inline components/service/components/ServiceDetails.jsx:149]: It should be conditional rendering, if link is present only render the button then.

**Review by njmulsqb — CHANGES_REQUESTED** [review]

File: components/service/components/ServiceDetails.jsx (hunk 1 above)
Comment (saadamir3180) [reply components/service/components/ServiceDetails.jsx:149]: are you referring to the conditional rendering of `Link` instead of complete `div` which is treated as a button?

Comment (saadamir3180) [reply components/service/components/ServiceDetails.jsx:149]: I think, instead of rendering conditionally, we should just disable the button, as done in other parts of the site. This will help maintain consistency in design.
e.g
image

Comment (njmulsqb) [reply components/service/components/ServiceDetails.jsx:149]: right

Comment (saadamir3180) [reply components/service/components/ServiceDetails.jsx:149]: Okay, moving forward with the second approach.

**Review by MZ-AD — APPROVED** [review]

**Review by njmulsqb — APPROVED** [review]
